### PR TITLE
Fix branch name for cppcoro

### PR DESCRIPTION
**Pull request by zheltkov**
Rename master to main

### CODE REVIEW

**Review by DoomHammer — APPROVED** [review]

**Comment by DoomHammer** [comment]
Hi @zheltkov !

Thanks for your PR. Could you rebase on top of the current master branch so the checks shall pass?

**Comment by zheltkov** [comment]
Done

**Comment by DoomHammer** [comment]
I think we need it once more :)

**Comment by zheltkov** [comment]
Done :)

**Comment by DoomHammer** [comment]
Thanks so much!

**Pull request merged**
