### PR TITLE
Solved some CMake configuration issues

### PR DESCRIPTION
**Pull request by gbellizio**
Solved some CMake configuration issues
(tested on Fedora Linux 3.34 with conan 1.36.0 and CMake 3.19.7)
  * fixed Microsoft GSL package name in several CMakeLists.txt files
    (examples of chapters 5, 6, 8, and 10)
  * fixed grpc package version in Chapter14/conanfile.txt file

### CODE REVIEW

**Comment by gaal-dev** [comment]
-find_package(ms-gsl CONFIG REQUIRED)
+find_package(Microsoft.GSL CONFIG REQUIRED)

Hi. Have you tested your change on other Linux distributions? This code was tested on Ubuntu.

**Comment by gbellizio** [comment]
No, but accordingly to the CMake configuration scripts generated by conan, the package name is Microsoft.GSL. 

For example in Microsoft.GSLTargets.cmake:

````
if(NOT TARGET Microsoft.GSL::GSL)
    add_library(Microsoft.GSL::GSL INTERFACE IMPORTED)
endif()

if(NOT TARGET Microsoft.GSL::Microsoft.GSL)
    add_library(Microsoft.GSL::Microsoft.GSL INTERFACE IMPORTED)
endif()                                      # package_name
````

Maybe a conan issue?

**Review by AndreasHAFischer — APPROVED** [review]
I tested this change on Windows 10 and Ubuntu 21.10.

**Comment by DoomHammer** [comment]
@aostrowski can you take a look?

**Pull request merged**
