### PR TITLE
fix ch02

### PR DESCRIPTION
**Pull request by gaal-dev**
Hi. I have fixed two examples from the 2nd chapter.

### CODE REVIEW

**Comment by gaal-dev** [comment]
ch02/grpc/service.proto
syntax = "proto2";

I had no time to check why AsyncClient crashes if syntax = "proto3" is used.

**Comment by aostrowski** [comment]
Most code from this chapter was moved to later ones written by Piotr so I'm assigning him. Also, we avoid Makefiles in our book because they're not portable in favor of CMake. I can help with providing CMakeLists for those changes.

**Comment by gaal-dev** [comment]
I can write CMakeLists and fix code a bit later.

I am also interested in the 5th chapter. It contains modules, but GCC 11 doesn't compile that code. I used an experimental build on Ubuntu because this version has not been released yet.

https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test

**Comment by aostrowski** [comment]
Awesome, thanks. You can peek at chapter 8 if you want to keep your CMake
style consistent with the rest of the book.

Regarding GCC11, I'm glad that it's finally available in a PPA as I had to
compile GCC trunk from sources. The code compiled on my build. Can you send
me the error message?

**Comment by gaal-dev** [comment]
> Can you send me the error message?
Yes, I can

gcc (Ubuntu 11-20210112-0ubuntu2) 11.0.0 20210112 (experimental) [master revision 1aff68d54c3:d081f4833df:248feb2fa2c0dfc8950566010b30351879c9d057]

GitHub breaks line endings.

`$ cmake --build .
Scanning dependencies of target 5_modules
src/5_modules/merchant.cpp:3:1: error: global module fragment contents must be from preprocessor inclusion
    3 | export module
      | ^~~~~~
src/5_modules/merchant.cpp:3:1: error: ‘export’ may only occur after a module interface declaration
src/5_modules/merchant.cpp:3:8: error: ‘module’ does not name a type
    3 | export module
      |        ^~~~~~
src/5_modules/merchant.cpp:3:8: note: ‘module’ was not recognized as a module control-line
src/5_modules/merchant.cpp:6:1: error: ‘export’ may only occur after a module interface declaration
    6 | export struct Merchant {
      | ^~~~~~
In module imported at src/5_modules/store.cpp:11:8:
merchant: error: failed to read compiled module: No such file or directory
merchant: note: compiled module file is ‘gcm.cache/merchant.gcm’
merchant: note: imports must be built before being imported
merchant: fatal error: returning to the gate for a mechanical issue
compilation terminated.
In module imported at src/5_modules/main.cpp:11:1:
store: error: failed to read compiled module: No such file or directory
store: note: compiled module file is ‘gcm.cache/store.gcm’
store: note: imports must be built before being imported
store: fatal error: returning to the gate for a mechanical issue
compilation terminated.
gmake[2]: *** [CMakeFiles/5_modules.dir/build.make:76: CMakeFiles/5_modules] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:105: CMakeFiles/5_modules.dir/all] Error 2
gmake: *** [Makefile:103: all] Error 2
`

**Comment by aostrowski** [comment]
Looks like a compiler bug that showed up when the code was formatted. I pushed d807cf5 to fix this. Try compiling now.

**Comment by gaal-dev** [comment]
Much better now:) The code has been compiled successfully. But executing 5_modules caused its crash.
`Segmentation fault (core dumped)`

**Comment by gaal-dev** [comment]
It seems GCC 11 is unstable. It often returns something like this when I change the code.

`free(): invalid pointer
malloc(): unaligned tcache chunk detected
c++: internal compiler error: Aborted signal terminated program cc1plus
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-11/README.Bugs> for instructions.
gmake[2]: *** [CMakeFiles/5_modules.dir/build.make:76: CMakeFiles/5_modules] Error 4
gmake[1]: *** [CMakeFiles/Makefile2:105: CMakeFiles/5_modules.dir/all] Error 2
gmake: *** [Makefile:103: all] Error 2`

This function "Stores get_favorite_stores_for(const CustomerId &customer_id) {" crashes 5_modules. I found that these two lines is the reason.
`.date_added = system_clock::now() - 1h,
.date_added = system_clock::now() - 12min,`
Segmentation fault (core dumped)

I removed 1h and 12min and the application worked that's so strange.
`.date_added = system_clock::now(),
.date_added = system_clock::now(),`

name: Handmade painted ceramic bowls, photo_url: http://example.com/beautiful_bowl.png, description: Hand-crafted and hand-decorated bowls made of fired clay, price: 1.230000, date_added: Thu Jan 21 09:58:09 2021 +03, featured: 1
name: Oscypek, photo_url: missing, description: Tasty smoked cheese from the Tatra mountains, price: 1.230000, date_added: Thu Jan 21 09:58:09 2021 +03, featured: 1

**Comment by gaal-dev** [comment]
I created a new pull request with CMakeLists

**Comment by gaal-dev** [comment]
See another pull request

**Pull request closed without merging**
